version: '3.8'

services:
  api_gateway:
    build: ./api_gateway
    ports:
      - "8000:8000"
    environment:
      - USER_SERVICE_URL=http://user_service:8001
      - PRODUCT_SERVICE_URL=http://product_service:8002
      - ORDER_SERVICE_URL=http://order_service:8003
    depends_on:
      - user_service
      - product_service
      - order_service

  user_service:
    build: ./user_service
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=sqlite:///./user_service.db

  product_service:
    build: ./product_service
    ports:
      - "8002:8002"
    environment:
      - DATABASE_URL=sqlite:///./product_service.db

  order_service:
    build: ./order_service
    ports:
      - "8003:8003"
    environment:
      - DATABASE_URL=sqlite:///./order_service.db

networks:
  default:
    driver: bridge